data/members.json

Github web-ui added the end-of-file marker.

Add dominicclifton and jflyper to contributors.

---

site.config.js
src/js/util.js

More estensible so that in the future if we have various different types they can be easily incorporated. It also cleans up the site.config.js

Updating method for generating links and news

---

scripts/build.sh

- is creating a list of all the paths from the linux container, this now passes /*

Path on the distribution

---

src/assets/js/main.js

Fixed mobile nav button behavior when any nav menu item is selected.

Fixed mobile nav button change behavior

---

src/pages/index.ejs

1. Improve **Latest News** section on the homepage. 
- Articles are displayed as cards.
- Article preview images are displayed in a 4:3 aspect ratio and they will fill the height and width of the box. 
2. Improve **About** section on the homepage.
- Accordion style content.
3. Make some paragraphs stand out by adding the .lead class.

Ui improvements

---

src/pages/index.ejs

Adds links to the latest lua scripts release and nightly builds.

Link to lua scripts

---

src/assets/css/bootstrap.css
src/assets/css/main.css

Some fixes for images height and video height/width for android.

Css fixes for images and videos

---

src/assets/css/bootstrap.css

My bad, i have added overflow for media min 576px, should be for max 576px

Fix overflow position

---

src/pages/index.ejs

Replaces bardwells 4.3 betaflight series of videos with Limons

Replacing beginner video with Limon's

---

docs/documentation/Release Notes/Betaflight 4.4 Release Notes.md

* Create Betaflight 4.4 Release Notes.md
Co-authored-by: Steve Evans <Steve@SCEvans.com>
Co-authored-by: Ivan Efimov <gendalf44@yandex.ru>
Co-authored-by: ctzsnooze <chris.thompson@sydney.edu.au>

Betaflight 4.4 Release Notes (#12176)

---

docs/configurator/power-battery-tab.mdx
docusaurus.config.js
package-lock.json
package.json
src/css/tailwind.scss

Was not exactly sure about some parts as I usually very rarely touch stuff here, please review and edit accordingly

Added Power & Battery tab, added KaTeX support

---

docs/documentation/FC LEDs.md
docs/documentation/Manufacturers/Manufacturer Design Guidelines.md

Hardware documentation for manufacturers, and user documentation.

Add LED documentation

---

docs/configurator/configuration-tab.mdx
docs/configurator/motors-tab.mdx
docs/configurator/ports-tab.mdx
docs/configurator/receiver-tab.mdx
docs/configurator/servos-tab.mdx
docs/configurator/setup-tab.mdx

My first docs update. Apologies if there are style/format errors present.

Configurator updates for receiver, motors, servos

---

docs/manufacturer/Manufacturer Design Guidelines.md

Update hardware spec

---

docs/development/API/Cloud-Build-API.mdx
docs/development/development.mdx
docs/manufacturer/manufacturer-design-guidelines.mdx
docs/release/Betaflight 4.4 Release Notes.md

Fixes: #129 
Fixes: #131 
Fixes: #133
They were already approved but now there is no need to rebase.

## Update Content

---

docs/wiki/archive/GPS-Rescue-v4-4.md

Some updated text for GPS Rescue

update GPS Rescue 4.4 notes CT

---

docs/wiki/configurator/firmware-flasher-tab.mdx

- Move Custom Defines to Other Options
- Add Expert Section for custom defines, commit field and local flashing

Update firmware flasher tab

---

docs/wiki/archive/GPS-Rescue-v4-4.md

Clarifies the GPS Rescue RTH Debug information.

update notes for GPS Rescue 4.4 wiki RTH section

---

docusaurus.config.js
src/css/tailwind.scss

Found a small bug in the setup of the Katex stylesheet.

Fix Katex Stylesheet

---

tools/check_file_names.mjs
tools/check_title_case.mjs

fixes false positive failing checks, when no errors occured

fix false negative checks

---

docs/manufacturer/connector-standard.mdx
docs/manufacturer/manufacturer-design-guidelines.mdx

Betaflight Connector Standard

---

docs/manufacturer/connector-standard.mdx

Reverts Ground Voltage to Voltage Ground pinout

Update connector standard

---

docs/development/development.mdx
docs/manufacturer/Approved.mdx
docs/release/Betaflight-4.4-Release-Notes.md
docs/wiki/configurator/firmware-flasher-tab.mdx
src/components/Home/index.tsx
src/pages/partner.mdx
tools/check_title_case.mjs

Fixes https://github.com/betaflight/betaflight.com/issues/159
Also includes formatting and other minor fixes.

Remove slack link

---

docs/wiki/configurator/motors-tab.mdx

Linked to EDT spec to make it easier for pilots and manufacturers to learn about EDT.

Add EDT description and link to EDT spec

---

static/img/betaflight/sponsors/dogcom.svg
static/img/betaflight/sponsors/hqprop.svg
static/img/betaflight/sponsors/radiomaster.svg

Fixes the logo's resolutions, which were displayed as 0px x 0px

Fix sponsor logo size

---

docs/wiki/configurator/motors-tab.mdx

Note that Air-Mode is nonfunctional with 3D mode and how to work around this.

3D mode and Air Mode notes

---

docusaurus.config.js
package-lock.json
package.json
src/pages/nivoTheme.js
src/pages/stats.tsx

Feature: Stats page

---

docs/development/Gps.md

Add more details about GPS / UBX in general and align the doc with the current code.
As per https://github.com/betaflight/betaflight/issues/12954
Readable version here https://github.com/adam-ah/betaflight.com/blob/master/docs/development/Gps.md

Updating documentation on GPS to match code and ublox recommendations.

---

src/components/Home/index.tsx

Fixes initial color mode, now it reads status and shows correct colorMode.

Fix initial colorMode

---

docusaurus.config.js

Added srcDark variable to allow navbar icon change when color theme is changed.

Fix navbar icon for dark/light mode

---

docs/wiki/archive/Magnetometer-v4-6.md

warning tag was too long, sorry

fix warning sign

---

docs/manufacturer/crearing-configuration.mdx

Starting documentation for details about a firmware 4.5 configuration file.

Add configuration details for firmware 4.5

---

docs/manufacturer/creating-configuration.mdx

I have trouble understanding the new TIMER_PIN_MAP commands and perhaps others do as well, so I have added some explanation. This is written by someone with a loose understanding but I hope it adds more information for others.

Explain timer pin map command structure

---

docs/development/development.mdx
docs/wiki/wiki.mdx

There is a caution that...
```
This site is still new. Very new. As of writing this, it's only 5 days since we started working on it. So it's still very much a work in progress.
```
I've changed this to...
```
This site is still new and is very much a work in progress.
```
Screenshot from the website:

Update caution as the site is more than 5 days old

---

docusaurus.config.js

Sort the items under "release" in descending order.

Put newest release first

---

blog/HQProp - Development Team Sponsor Review.md

First attempt at blog entry for HQ

HQ Prop Blog Entry

---

docs/development/Gps.md

Update GPS documentation

---

docs/manufacturer/manufacturer-design-guidelines.mdx

Fix defines in manufacturer-design-guidelines.mdx

---

docs/tuning/3.5-tuning-notes.md
docs/tuning/4.2-Tuning-Notes.md

fix link syntax in two tuning guide documents

---

docs/wiki/release/Betaflight-4.5-Release-Notes.md
docusaurus.config.js
package-lock.json
package.json

By adding this configuration, the markdown processor will convert `@username` mentions into clickable links that point to the GitHub user profiles.

Add GitHub username links

---

src/css/mermaid.scss

Style Fix: Use consistent borders for clusters and nodes

---

tailwind.config.js

not sure if it's useful, but helps perhaps

annotate colours so we know what they are

---

.github/workflows/docs.yaml

Forgot to update workflow as it did not throw any errors - only a warning - we did not notice.

Update node in docs.yaml

---

src/css/tailwind.scss
src/theme/DocCard/index.js
src/theme/DocCard/styles.module.css
src/theme/DocCardList/index.js

Style: Change doc card spacing and layout

---

tailwind.config.js

Added notes about an HSL colour viewer, colour formats, and tidied up.
No code changes, just comments.

note about colour formats

---

docs/wiki/guides/current/DSHOT-RPM-Filtering.md

Wondering if this is the best place to add date or perhaps this should be a separate page?

Add ESC firmware version tables and more information

---

docs/development/Modes.md
docs/wiki/configurator/auxiliary-tab.md

Update missing modes
Mention categories 
Depend of https://github.com/betaflight/betaflight-configurator/pull/3583

Update mode tab with categories and new modes

---

docs/relations/sponsors.mdx
docs/wiki/boards/KAKUTEH7V2.md

Replace `https://https://` with `https://`, probably a copy-paste error.

Fix link scheme

---

docs/wiki/configurator/auxiliary-tab.md

Sorry saw categories mentioned after merge. This will cleanup for now.

Cleanup auxiliary-tab.md

---

docs/wiki/guides/current/Magnetometer.md

fix magnetometer page typos

---

docs/wiki/guides/current/Magnetometer.md

The IST8310 Mag can have any one of four 12c addresses. The default is 12, but it could also be 13, 14 or 15.  At least one integrated GPS module, the GEP-M1025-MI, uses 14.
This PR clarifies i2c a bit better, and provides information about how to handle Mag units that are not detected, as well as specific notes about the IST8310.
Sure would be easier to explain i2c if we used the term 'bus' instead of 'device' when we refer to the Flight Controller's physical i2c bus to which Mag or Baro devices are connected.

Update mag i2c and IST8310 notes

---

docs/development/Git.md

* formats git recommendations as code
before
after

format git recommendations

---

docs/wiki/boards/TMOTORF7.md

- https://github.com/betaflight/betaflight.com/issues/224#issuecomment-1884952853

update TMotorF7 IMU list

---

docs/development/VTX.md
docs/wiki/configurator/firmware-flasher-tab.md

- Flashing tab: minor spelling correction
- VTX tab: betaflight not cleanflight

minor corrections

---

docusaurus.config.js

This adds the script for simple analytics using the TelemetryDeck product (also used by the build server, and build API).

Adding the script for analytics

---

src/components/Home/index.tsx

correct Betaflight Partner Link

Fix Homepage Link for Partners

---

docs/relations/sponsors.mdx
src/components/Home/index.tsx

dogcom updated their website address this should fix it. my first pr in the .com so hopefully I gots it right :)

change dogcom web address 

---

docs/development/EXST-Bootloader.md

fix typo in EXST-Bootloader.md

---

docs/development/LedStrip.md

fix typo in [LedStrip.md]

---

docs/development/CodingStyle.md

fix typo in [CodingStyle.md]

---

docs/development/Boards.md

Update [Boards.md] fix typo

---

README.md

This pull request aims to enhance the documentation for the Betaflight.com project by addressing identified gaps and improving clarity and usability. It includes a variety of enhancements, such as providing a concise project description, detailed installation instructions, troubleshooting guidance, contributing guidelines, and more. These changes aim to make the documentation more comprehensive and user-friendly, enabling users to better understand the Betaflight.com project and effectively contribute to it.
- **Image And Discord Badge:** Included the Betaflight logo and the Discord badge.
- **Project Description:** Added a clear overview of the website's purpose and target audience.
- **Table of Contents:** Included for better organization and navigation.
- **Installation and Setup:** …

Enhance README.md Documentation: Improved Project Description, Installation Instructions, Troubleshooting, and Contributing Guidelines

---

docs/development/manufacturer/manufacturer-design-guidelines.md

I was asked to provide some guidelines for the ICM42688P and other ICM42xxx IMU. This is what I have. Should anything be added and is it in the correct place? 
@sugaarK

IMU power supply info note

---

docs/wiki/guides/current/Telemetry.md

Telemetry updated for CRSF info

Telemetry update

---

docs/development/building/Building-in-Mac-OSX.md

Fix Xcode name

---

docs/wiki/boards/OMNIBUSF4SD.md

Just adds a note for people whose i2c appears not to work.
May need updating later if more clarity about i2c emerges.

Add OmnibusF4SD target note

---

docs/development/API/Dshot.mdx
docs/development/manufacturer/connector-standard.md
docs/relations/sponsors.mdx
package-lock.json
package.json
src/components/Home/index.tsx
src/components/Sponsors/Sponsors.tsx
src/css/custom.css
src/theme/Footer/Layout/index.js

Replaces the hard-coded banner
Thanks a lot to @freasy for showing me how to do it and for making sense of React in general

Fetch sponsor banner from BF server

---

src/pages/download.tsx

To include the links to the live versions of the app and blackbox viewer.

Update download page

---

docs/wiki/guides/current/SoftSerial.md

Update softserial.md for smartport override

---

src/components/Sponsors/Sponsors.tsx
src/css/custom.css

Separates the logos a bit more

More space between sponsor logos

---

docs/wiki/release/Betaflight-4-5-Release-Notes.md

Added some notes about setting Rates in Angle mode, and updated the referenced PR with more details and some graphics.
Many thanks to @haslinghuis for improving the graphics in Configurator.  This makes life much better for Angle Mode users.

small Angle Mode notes change

---

docs/wiki/release/Betaflight-4-5-Release-Notes.md

https://discord.com/channels/868013470023548938/996119401269047397/1234158927172730930

RN 4.5, BBE/gyro_scaled verbiage

---

docs/wiki/guides/current/FAQ.md

- fixes https://github.com/betaflight/betaflight/issues/13642

Update FAQ [MSP over UART]

---

docs/wiki/guides/current/Broken-USB-Rescue.md

Guide how to rescue a FC with broken USB Port, incl. how to build a rescue firmware.

Guide: Broken USB Rescue

---

docs/development/manufacturer/connector-standard.md

- added warning about potential damage for 6 pin.

Updating GPS connector, and adding SWDIO.

---

docs/development/manufacturer/requirements-for-submission-of-targets.md

https://deploy-preview-437.dev.web.betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets

update target requirements

---

docs/development/Boards.md

Fixed broken links to boards

---

docs/development/manufacturer/creating-configuration.md

Hello!
Found a broken link on "How to Create a Flight Controller Configuration File for Betaflight 4.5" page.

Fixed a broken link in "How to Create a Flight Controller Configuration File for Betaflight 4.5" page

---

docs/wiki/configurator/motors-tab.md
docs/wiki/getting-started/setup-guide.md
docs/wiki/getting-started/troubleshooting.md
docs/wiki/guides/current/DSHOT-RPM-Filtering.md

Regression from https://github.com/betaflight/betaflight.com/pull/231
edit: found another broken url, adding it here instead of a new PR

Fix modes tab & esc url

---

docs/development/SITL.md

Resolves https://github.com/betaflight/betaflight-configurator/issues/4215

SITL 4.6 websocket requirement

---

docs/development/building/Building-in-Fedora.md
docs/development/building/Building-in-Ubuntu.md

* just updating some info
* ideally, all these building documents need unification and updating (outside of this PR scope).

update versions for building info

---

docs/development/manufacturer/manufacturer-design-guidelines.md

Forgot to update the changelog in https://github.com/betaflight/betaflight.com/pull/511

Forgot to update changelog

---

docs/development/Mixer.md

- see also https://github.com/betaflight/betaflight-configurator/pull/4319

Update required motors custom airplane

---

docs/development/building/Dfu_Flash.md

- resolves https://github.com/betaflight/betaflight/issues/14234
- preview link: https://deploy-preview-527.dev.web.betaflight.com/docs/development/building/Dfu_Flash

add dfu_flash documentation

---

docs/development/Serial.md

resolves https://github.com/betaflight/betaflight.com/issues/520

replace dead Example-Serial-Device links with google search links

---

docs/development/SITL.md

SITL instructions were missing some key steps

Improve SITL instructions

---

docs/development/manufacturer/connector-standard.md

Doh! Forgot to remove the one line I wanted to remove.

Remove proposal

---

src/theme/Footer/Layout/index.js

now powered:
- by cloudflare pages for PR previews, and
- by AWS S3/cloudfront for apex domain.

Remove reference to netlify

---

docs/wiki/guides/current/PID-Tuning-Guide.md

Remove dead link, use english, fix layout
