src/layouts/article.ejs
My bad, seems that `articles` uses another independent Header, fixed it now.
=> Fixed logo Href for articles

src/assets/css/main.css
I have changed logo units to relative units and container text size based, it helps to adapt logo size with diferent devices and web Browsers. Also fixes no logo appears for Firefox Browser.
=> Changed logo size units to relative units

src/assets/css/bootstrap.css, src/assets/css/main.css, src/pages/index.ejs
This PR moves article img styles to css file and changes this img style for phones. Also fixes overflow text in banner area.
=> Fix banner area text and articles images height for phones

readme.md, src/layouts/default.ejs, src/pages/index.ejs
There were two sections on the home page that were not called out in the menu. To add some clarity I added the menu item "Beginners Tutorial" which will navigate the user to Bardwells Playlist of 4.3 tutorials. The 4.2 tutorial was a single video which could be linked to and now that the tutorial is a playlist, the tutorials are included by using an iframe. The other menu item added is "Get Betaflight" which will navigate the user to a section that has links to install the latest configurator, releases, blackbox etc. 
I don't know that I'm keen on the ordering of the menu items. If someone has a better arrangement it's an easy change.
also addresses issue #73 Replace the outdated Video on the index page with Joshua Bardwells new Betaflight 4.3 Tutorial series
=> Adding Menu Items "Beginners Tutorial" and "Get Betaflight"

docs/configurator/configuration-tab.mdx, docs/configurator/ports-tab.mdx, docs/configurator/receiver-tab.mdx, docs/configurator/setup-tab.mdx
I think it's best we use [title case](https://www.computerhope.com/jargon/t/title-case.htm) for all headers going forward
=> Title case for consistent headers

.github/workflows/docs.yaml, blog/authors.yml
Before the CNAME file was mandatory for the custom domain setting for github pages.
Since i didnt know, i missed to copy it into the correct branch.
=> fix github deploy action so it includes CNAME to not break on deployment

docs/documentation/Release Notes/Betaflight 4.4 Release Notes.md, docs/old/autonomous/GPS-Rescue-Mode-for-4-1-to-4-3, docs/old/autonomous/GPS-Rescue-for-4-4
Fixed defines for FLASH.
Added missing docs for `GPS-RESCUE` as they were using a dot in their name they were missed.
=> Update RN and add missing GPS Rescue docs

docs/wiki/configurator/firmware-flasher-tab.mdx
=> Remove launch control and style fixes

docs/wiki/misc/mdx-reference.mdx
Some beautifications in `/docs/wiki/misc/mdx-reference.mdx` and a new paragraph to demonstrate how to render mathematical equations
=> Update MDX reference

docs/tuning/4.3-Tuning-Notes.md, docs/wiki/wiki.mdx
Added a link to this repo on the main page.
Changed "centre" to "center" in 4.3 tuning notes.
=> Repo link and "center" changes

docs/release/Betaflight 4.4 Release Notes.md
- Add link to PR #11857 which is also relevant
- Remove 'when airmode is active' from header since both airmode on and off were affected
- Add 'gyro rates' to header since the bugs occurred at saturation, especially when all three axis had high errors at the same time.
=> Correction to 4.4 release notes about mixer throttle adjustments

docs/wiki/boards/Missing.md
In solution to betaflight-confirgurator issue (#3521)
This file are used when no documentation are found a board
File: https://betaflight.com/docs/wiki/boards/missing.md
Suggestion for content:
---
Betaflight wiki currently has no description for this board.
You can try to find a previous board / board version from same Manufacturer at [https://betaflight.com/docs/wiki/boards](https://betaflight.com/docs/category/boards)
You can ask the Manufacturer to add this description as described in [https://betaflight.com/docs/manufacturer/manufacturer-design-guidelines](https://betaflight.com/docs/manufacturer/manufacturer-design-guidelines)
=> Add Missing board file

docs/wiki/archive/Bidirectional-DSHOT-and-RPM-Filter.md
Updated to reflect the change made in 2019 where dshot telemetry was delayed by 30us instead of 25us to allow for 8bit MCUs (https://github.com/betaflight/betaflight/pull/8554#issuecomment-512507625).
=> Dshot timing

docs/wiki/archive/GPS-Rescue-v4-5.md
Sorry there was a formatting error that accidentally crept in at the top of the last GPS Rescue Wiki PR.
Took the opportunity to make some small changes also.
=> fix the WARNING sign covering the next two sections

docs/wiki/archive/Magnetometer.md
For the Compass wiki entry:
- restores the `.md` file type, not `.mdx`, because I cannot make commits if the file type is `.mdx`
- fixes an issue caused by the checking code, where any caution or warning text terminators `:::`, that are placed immediately after a bullet list, will be modified by the checking code so that they get  preceded by two spaces.  The terminators then have no effect.  Solution was to manually put a line break ahead of the affected terminators.
- updates information about the different internal scaling factors, and axis orientation of some Mag units
- includes information about declination and configuring the declination correction factor in the CLI
=> fix warning and caution

docs/wiki/archive/Magnetometer.md
Minor update of the mag calibration process to align with the recently merged [PR 12998](https://github.com/betaflight/betaflight/pull/12998)
In view of the dubious nature of the old driver code for the AK8963 and AK8975 (see comments from ledvinap on the mag scheduler firmware PR), I added a 'caution' flag indicating that these drivers were deprecated and that they may not work or may cause other i2c issues.  
At this point the only mag with exhaustive testing is the QMC5883L.  Others should work but no-one seems to have time to test them.
=> Calibration notes update

docs/wiki/archive/Magnetometer.md
Since firmware PR 12998 was merged, providing enhanced Mag Calibration, a tap on the frame is needed to initiate the data acquisition part of the calibration process.  This PR explains how to do it, and performs some editorial enhancements.
=> Update magnetometer wiki to better explain calibration initiation

docs/wiki/archive/GPS-Rescue-v4-5.md
The GPS Rescue notes had a 'warning' tag that didn't clear properly.
It seems that those kinds of tags must have spaces to separate them if all the content is a list.
Fixed.
=> fix warning tags and add power on message

docs/release/Betaflight-4.5-Release-Notes.md
4.5 release notes.
<sorry guys, made a mistake and had to force push - lost your approvals - won't make any more changes to this PR until merged>
No intention whatsoever of omitting people that deserve a mention, please hit me up for all the things I've missed.  Suggestions to improve the document can be sent to me over discord or added here.
Click [here](https://github.com/betaflight/betaflight/pulls?q=is%3Apr+milestone%3A4.5) for a full list of all PR's tagged for the 4.5 milestone.  This may include some that were closed before merging, or were not merged.
=> 4.5 release notes

docs/release/Betaflight-4.5-Release-Notes.md
A first update to the release notes for 4.5:  This PR is ready to merge.  Won't change it - please merge ASAP.
- made consistent "Thanks to: " etc
- added contributors
- warning about more than one ADC on AT32
- warning about Rainbow LED effect
- added coloured text in OSD HD
- improved and updated RPM LIMITER information - thanks @limonspb 
- added pre-arm race OSD display
- added info about within-Blackbox GPS Mapping from @bonchan (awesome!)
=> 4.5 release notes update 1

docs/release/Betaflight-4.5-Release-Notes.md
Incremental update to the 4.5 release notes
- adds a contents list
- adds the recent Ledstrip CPU usage fix and amends the rainbow note about CPU usage
- improves the top of the page a bit
- other small clarifications
Will rebase if needed because of structural changes.
=> 4.5 release notes update 2

package-lock.json, package.json, src/components/VersionInfo/VersionInfo.tsx, src/theme/DocItem/Layout/index.js, src/theme/DocItem/Layout/styles.module.css
Add
```
sidebar_custom_props:
versionGte: 3.5
versionLte: 4.5
```
to the doc page frontmatter metadata with any version number needed, it will render out into this:
=> Feature: Add GT and LT version labels

docs/wiki/getting-started/index.md
Hi guys
>after recent merges, all we need is to change the index document attributes to avoid the duplication of the file name.
original comment:
It loads 'index.md' (which is the old Getting Started document, re-named) when the user clicks on the `Getting Started` sidebar element.  Instead of just showing the contents of the directory, which we already see below `Getting Started` anyway.
The other three documents in the directory appear under the heading.  
Hence each sidebar element has its own unique page, and the page to the right of a sidebar header also can be more useful.  I've done something similar with the Guides section in a recent PR.  To avoid re-duplicating the main page name at the top, I gave it an ID and a title.
Not sure if this is the recommended way, but it works :-) …
=> Give getting started a default index page, and update it a little

docs/wiki/guides/current/Magnetometer.md, src/css/tailwind.scss
The current drop shadow is bright orange and hard.
This changes to the 'boring' but less intrusive pale grey shadow.  Only negative is that in night mode there is no shadow.
This adds a 6px margin around images, which were jammed up against text.
Also fixed the image in magnetometers to centre it properly.
and a simple left-oriented image
current hard orange shadow
=> drop shadow simplification, margin around image

src/css/tailwind.scss
Code blocks were rendering much larger than normal text size.
This makes them 'x-small' using the 'xs' attribute.
And modified the margins.
This is normal, as in master, code blocks quite a lot bigger than normal text, and quite a lot of padding and margin:
As per this PR I think it's a bit easier to scan the code blocks, especially inline.
=> reduce code block to sm size

docs/development/mdx-reference.md, docs/relations/partner.md, docs/wiki/release/Betaflight-4.4-Release-Notes.md, docs/wiki/release/Betaflight-4.5-Release-Notes.md, src/components/Home/index.tsx, src/components/HomepageFeature/index.tsx, src/components/RecentPosts/index.tsx, src/components/Team/index.tsx, src/css/mermaid.scss, src/css/tailwind.scss, src/pages/download.tsx, src/pages/stats.tsx, src/theme/Footer/Links/MultiColumn/index.js
This PR shifts the default orange colour used for text to one step darker, to improve legibility.
Small link text is still a bit difficult to read, especially in daylight mode, and in particular when the orange text is over a pale orange or grey background.
Reduced the heading sizes and made them all orange, with consistent space before and after.
Text colours before:
Text colours after:
With smaller H1 and H2, and modified line spacing for headings
With new text colours, night mode still looks good:
Also I noted that after a numbered list, text, even with a clean new line above it, gets too close.  I don't know the solution to it but I made a note in the mdx reference.
=> Make orange text darker and tighten up heading spacing

docs/relations/sponsors.md
Was unintentional removed in https://github.com/betaflight/betaflight.com/pull/277/files
Thanks to @VitroidFPV for spotting this.
=> Restore Radiomaster in sponsors tab

src/pages/developer.js, src/pages/development.js, src/pages/help.js, src/pages/sponsors.js
Configurator wants to send the `betaflight.com/sponsors` URL to open our Sponsors page.
Currently our Sponsors page is the file `Sponsors.md` in `betaflight.com/docs/relations/`, which has an auto-generated docusaurus id of `sponsors` and is set to the top sidebar position (0).
When the user clicks `Relations` in the website, the file `/docs/relations/Sponsors.md` is opened, and the URL at the top of the browser is shown as `https://betaflight.com/docs/relations/sponsors`.
This PR provides a simple javascript redirect at `src/pages/sponsors.js` to `/docs/relations/sponsors/`.
With this, the URL `https://betaflight.com/sponsors` or `https://betaflight.com/sponsors` will directly open the Sponsors page, instead of generating a 'Page not found' error.
I did the same for /help, /developer, …
=> Implement basic directory-only redirects

src/pages/developer.js, src/pages/development.js, src/pages/help.js, src/pages/sponsors.js
Reverts betaflight/betaflight.com#297 to fix
```
Error: Docusaurus server-side rendering could not render static page with path /developer because of error: window is not defined
It looks like you are using code that should run on the client-side only.
To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).
It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).
at serverEntry_render (main:190553:358)
at async /home/runner/work/betaflight.com/betaflight.com/node_modules/p-map/index.js:57:22 {
[cause]: ReferenceError: window is not defined
at 48012 (main:194744:1)
at …
```
=> Revert "Implement basic directory-only redirects"

src/pages/help.js
The previous PR #297 failed on build, and I think it was because the redirection code was the only content of the javascript file.  There was no page containing the redirection, and I think that caused the error.
The javascript in this PR makes a page, using the standard docusaurus test file (which I confirmed works), and then puts the redirect code into the page.  I am optimistic that by generating a 'static' page this way, the previous build error will not occur.  
This PR only adds one redirect, from `betaflight.com/help` to `/docs/wiki/getting-started/`.
If this works, I can PR the `support` fix later.
We have reverted the previous PR in #299
=> Try a different method for local redirect

docs/relations/sponsors.md
The text said three sponsors, updated to say four, which is the correct number.
=> fix incorrect sponsor count

src/pages/sponsors.md
This is a simple hack that, once merged, should provide resolution for the URL `https://betaflight.com/sponsors`, by simply putting a copy of our existing `/docs/relations/sponsors.md` markdown file into `/src/pages`.
It would be nicer if this could be done with some kind of alias, or programmatically, but for now, this should fix the issue where configurator links to `https://betaflight.com/sponsors` do not work.
=> Copy sponsors.md into pages directory, to provide a link for Configurator

src/components/AboutCard/index.tsx, src/components/HomepageFeature/index.tsx, src/pages/download.tsx, src/pages/stats.tsx
Downloads page:
- heading appearance consistent with other pages, in both font size and location
- duplicate headings removed
- text position changes less when resizing window
- links within text where possible, rather than separate objects which got squashed at some window sizes
- updated the text a little bit, mostly just editorial changes
- used our standard colour for the video header, and scaled the icon when smaller
Overall, there's more content and less distracting headings
Stats page:
- added blur behind the graphs
- made the headings consistent with Downloads and the other pages.
NB: didn't change the statistics code, which appears broken.
At typical laptop size, looks like this, with headings and text sizes the same as normal pages (updated text):
vs in master, used to look like …
=> Styling and text update for downloads page

docs/wiki/release/Betaflight-4-5-Release-Notes.md
- Correct spelling error (EzLanding, instead of ExLanding)
- Slightly more accurate description of what EzLanding does
=> Update EzLanding content entry in 4.5 release notes

src/components/Home/index.tsx, src/components/HomepageFeature/index.tsx, src/pages/stats.tsx
Header font size didn't get smaller with smaller screens.
This just reduces headers from 3xl to 2xl when the screen is smaller than 'md' size. No other changes.
New narrow appearance:
Older narrow screen appearance:
New main page when small:
Previous heading size:
=> Simple PR to make headers one size smaller on small screens

docs/development/manufacturer/manufacturer-design-guidelines.md
Wasn't sure where to put this, but under IMU seems best, without having to re-order all the subheadings.
The intent is to:
- recommend against using the Bosch BMI-270 gyro, which has been identified as having un-calibrated gyro data.  When the quad is turning more than 15 deg/s, integrated gyro data is used to determine the change in attitude of the quad.  Only when the rate of change is less than 15 deg/s will the accelerometer data be used.  Integration of the BMI-270 leads to up to 5% errors in angle estimate, and the result is that after a quick input, there will be a kind of 'jiggle' when the IMU shifts orientation back to the accelerometer value.  This is highly undesirable.  Hence I suggest that we strongly recommend against using the BMI-270
- recommend against using barometer …
=> Add note about BMP-270 gyro, DPS310 clone, IST8310 mag, to manufacturer guidelines

docs/development/mdx-reference.md
Added some notes about capitalisation in the MDX reference document, to help explain the recommended practice.
=> Capitalisation notes in mdx reference

docs/wiki/guides/current/Failsafe.md, src/pages/failsafe.js, src/pages/failsafe.md
Some discussion about the meaning of the message `NOT_DISARMED` led me to review the failsafe page.
updated the notes about that message, clarified arming blocks, did some capitalisation.
hopefully a bit more clear
also added a betaflight.com/failsafe shortcut.
=> Update failsafe with note about not disarmed message

docs/wiki/guides/current/Barometer.md
@SteveCEvans commented in the previous Baro update PR that I should explain how Baro and GPS are 'mixed' together to determine our altitude readings, so I have attempted to do so, in this PR.
=> Add notes about GPS vs Baro contributions to altitude estimation

docs/wiki/release/Betaflight-4-5-Release-Notes.md
`i-term at zero throttle for wings` is not an important change, moved it to the bottom of "Other changes"
=> Moved i-term at zero throttle for wings to other changes and fixes

src/theme/Footer/Layout/index.js
Starting to test out Netlify. In order to comply with the [Netlify Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/), there needs to be a link/badge like this one.
=> Content: Link to Netlify in the Footer

docs/wiki/guides/current/RunCam-Device-Protocol.md
Current
https://betaflight.com/docs/wiki/guides/current/RunCam-Device-Protocol#analogclassic-fpv-cameras
Fixed:
=> fix: runcam device protocol compatability table

docs/development/CodingStyle.md
The "Braces are required" heading is not rendered on betaflight.com/docs/development/CodingStyle:
This adds a space after `###` for the "Braces are required" heading, so it is rendered correctly on betaflight.com/docs/development/CodingStyle.  
It also adds an empty line after the heading, consistent with the other headings in the file.
A few other locations below are not rendering code correctly - before I add that change: should I be creating issues first?  Any preference if it is in same PR or should be separate?
=> Fixes markdown heading in CodingStyle.md

src/components/Home/index.tsx, src/components/Sponsors/PartnerOverview.tsx, src/components/Sponsors/SponsorBanner.tsx, src/css/custom.css
Makes it possible to fetch and display all the partners using `<PartnerOverview />`
=> Implement Partner Overview

docs/development/USB-Flashing.md
I strugged some hours to get my board into DFU mode as an ELRS receiver on UART1 was preventing it from entering DFU mode. Once you know the trick, its totally easy :-)
=> added info how to enter DFU mode

docs/development/manufacturer/requirements-for-submission-of-targets.md
* updated target submission requirements with simplified language.
* removed "legacy" verbiage. maybe prefer it not removed?
* in association with https://github.com/betaflight/config/pull/458
direct link to page: https://deploy-preview-427.dev.web.betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets
=> update target requirements

docs/wiki/guides/archive/Betaflight-4.0-CLI-commands.md, docs/wiki/guides/current/Betaflight-4.5-CLI-commands.md
* moves 4.0 CLI reference to archive.
* adds 4.5 CLI reference to current.
* needs facts checking (i simply copy/pasted `help` and `get` commands with minor alteration, using base `make FOXEERF405` hex).
direct Netlify link https://deploy-preview-431.dev.web.betaflight.com/docs/wiki/guides/current/Betaflight-4.5-CLI-commands
=> 4.5 CLI Reference

docs/development/manufacturer/manufacturer-design-guidelines.md
DFU pins were missing from F411 and F405 also.
https://www.st.com/resource/en/application_note/an2606-stm32-microcontroller-system-memory-boot-mode-stmicroelectronics.pdf
F405 on page 127, F411 on page 150.
=> Update DFU pins in manufacturer-design-guidelines.md

docs/wiki/guides/current/GPS-Rescue-v4-5.md
tiny change to GPS Rescue documentation for 4.5
In 4.5 the CLI command that added a Dilution Of Precision value after sats was changed from `osd_gps_sats_show_hdop` to `osd_gps_sats_show_pdop`.
See https://github.com/betaflight/betaflight/pull/13477.
I forgot to update the command in the documentation, this PR should correct it. A Facebook user noticed this.
=> change show_hdop to show_pdop

docs/development/manufacturer/fc_documentation/fc-doc-example.mdx, docs/development/manufacturer/fc_documentation/fc-doc-template.mdx.template, docs/wiki/boards/current/AIRBOTG4AIO/AIRBOTG4AIO.mdx, docs/wiki/boards/current/AIRBOTSUPERF4/AIRBOTSUPERF4.mdx, docs/wiki/boards/current/BRAHMA_F405/BRAHMA_F405.mdx, src/components/SpecGrid/SpecBox.tsx, src/components/SpecGrid/index.tsx
As suggested in #471 - info grid shouldn't overflow across all screen widths, also allows for other blackbox storage media (flash, emulated SD card, SD card, external logger only) to be properly mentioned. 
Will move on to fix #471 and #478 after this - their preview builds will fail for the moment, but both will be converted as well
=> Style: Fix info grid responsiveness, simplify info props

docs/wiki/configurator/power-tab.md
According to code it should be
But this one from @KarateBrot looks cleaner
=> Fix formula

docs/wiki/guides/current/Position-Hold-v4-6.md
First draft of a page for Altitude Hold and Position hold.
Needs work.
direct link: https://deploy-preview-494.dev.web.betaflight.com/docs/wiki/guides/current/Position-Hold-v4-6
=> Position Hold wiki page

docs/development/Serial.md
- add documentation for https://github.com/betaflight/betaflight/pull/14094
=> Add UART0 range

docs/wiki/release/Betaflight-4-5-Release-Notes.md
Betaflight Configurator nightly builds are now accessible from [app.betaflight.com](app.betaflight.com).
I've updated the link to the nightly build in `4.5 Release Notes`
=> Changed link for nightly configurator

docs/wiki/configurator/firmware-flasher-tab.md
- Renamed `Altitude Hold Mode` to `Altitude Hold` to match Betaflight Configurator
- Added Position Hold introduced in [#13975](https://github.com/betaflight/betaflight/pull/13975)
- Added missing Soft Serial option
- Added Wing introduced by [#14010](https://github.com/betaflight/betaflight/pull/14010)
=> Added missing "Other Options" in Firmware Flasher Tab

docs/wiki/guides/current/Crash-Recovery.md
Not sure what else to add.
Ideally, explain how to tune it, but in my testing, it hasn't been necessary for 75mm - 3.5 in quads.
Direct link: https://deploy-preview-508.dev.web.betaflight.com/docs/wiki/guides/current/Crash-Recovery
=> Wrote Crash Recovery page

docs/development/Battery.md
The battery charger measurement method to tune the amperage scale state the formula as:
```
amperage_meter_scale = old_amperage_meter_scale * (mAh_recharged / cleanflight_reported_mAh_drawn)
```
This is incorrect. The actual formula should be:
```
amperage_meter_scale = old_amperage_meter_scale * (cleanflight_reported_mAh_drawn / mAh_recharged)
```
=> Fixed incorrect formula to find new amperage scale using battery charger measurement in Wiki

docs/development/Serial.md
PR https://github.com/betaflight/betaflight/pull/14263 increases the number of msp ports via a custome define when building your target.
This PR updates the serial port references about the maximumun number of msp serial ports.
It's targeted for 4.6
=> Updating the serial port documentation on max number of msp ports

docs/wiki/guides/current/Mixer-Types.md
- add mixer_type EZLANDING link to Mixer-Types page.
preview link:  https://deploy-preview-526.dev.web.betaflight.com/docs/wiki/guides/current/Mixer-Types#mixer-type-ezlanding
=> add mixer_type EZLANDING/link

.github/workflows/deploy-preview.yml, .github/workflows/deploy.yaml
This pull request introduces a new GitHub Actions workflow for preview deployments and makes a minor improvement to an existing deployment workflow. The most significant change is the addition of the `.github/workflows/deploy-preview.yml` file, which automates the process of building and deploying preview environments for pull requests. Additionally, a small adjustment was made to the `deploy.yaml` workflow for consistency.
* **Added a new workflow file**: `.github/workflows/deploy-preview.yml` to automate preview deployments for pull requests targeting the `master` branch. This workflow includes steps for checking out code, caching dependencies, setting up Node.js, building the package, deploying to Cloudflare, and adding a deployment comment with a preview URL.
* **Renamed a step for …
=> Adding previews for PRs

docs/development/manufacturer/connector-standard.md
- adds specification for 10 pin ESC connector for additional power requirements
- adds dedicated 4 pin RC connector for CRSF, ELRS devices as this is a standard on itself
- add note about connector color and legacy connector provision
=> BFC: Add 10pin ESC and note about color and legacy wire harness
